apiVersion: v1
kind: Pod
metadata:
  name: myFirstK8Spod # pod name
  labels:
    app: myFirstK8Skube
spec:
  containers:
  - name: myFirstK8S_ex91 #container name
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
