apiVersion: v1
kind: Pod
metadata:
  name: myfirstk8spod # pod name
  labels:
    app: myfirstk8skube
spec:
  containers:
  - name: myfirstk8sex91 #container name
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
