apiVersion: v1
kind: Service
metadata:
  name: myfirstk8sser
spec:
  type: NodePort
  ports:
  - port: 8099
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  selector:
    app: myfirstk8skube