apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstk8sdep
spec:
  selector:
    matchLabels:
      app: myfirstk8skube
  replicas: 5 # Increase the number of pods (3->10->30->5)
  template:
    metadata:
      labels:
        app: myfirstk8skube
    spec:
      containers:
      - name: myfirstk8sex91
        image: nginx # Change to Nginx Container (httpd -> nginx)
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

