apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstk8sdep
spec:
  selector:
    matchLabels:
      app: myfirstk8skube
  replicas: 3
  template:
    metadata:
      labels:
        app: myfirstk8skube
    spec:
      containers:
      - name: myfirstk8sex91
        image: httpd
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
